name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake game from GitHub contribution grid
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: spatelpatidar
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light

      - name: Push generated files to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          keep_files: true